# Generated by Django 5.0.4 on 2024-04-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_correcao_prova_correcao_caderno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensino', models.CharField(max_length=200)),
            ],
        ),
    ]
