# Generated by Django 5.0.4 on 2024-04-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_weekday_planejamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSemana', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='planejamento',
            name='diaSemana',
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='WeekDay',
        ),
        migrations.AddField(
            model_name='planejamento',
            name='diaSemana',
            field=models.ManyToManyField(to='dashboard.dayofweek'),
        ),
    ]
