# Generated by Django 5.0.4 on 2024-04-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_dayofweek_remove_planejamento_diasemana_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayofweek',
            old_name='diaSemana',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='planejamento',
            old_name='diaSemana',
            new_name='days_of_week',
        ),
        migrations.RenameField(
            model_name='planejamento',
            old_name='descricao',
            new_name='name',
        ),
    ]
