# Generated by Django 5.0.4 on 2024-04-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_planejamento_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofweek',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
