# Generated by Django 5.0.4 on 2024-05-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_vestibular_urlimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestibular',
            name='desc',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
