# Generated by Django 5.0.4 on 2024-06-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_deck_descricao_alter_deck_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='pergunta',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='resposta',
            field=models.TextField(max_length=150),
        ),
    ]
